# Generated by Django 4.1.7 on 2023-04-25 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCuentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foto',
            old_name='titulo',
            new_name='cuento',
        ),
    ]
