# Generated by Django 4.1.7 on 2023-04-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCuentos', '0007_cuento_foto_delete_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuento',
            name='foto',
            field=models.ImageField(upload_to='fotos'),
        ),
    ]
